--[[
Copyright © 2017, Ivaar
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
* Neither the name of SkillChains nor the
  names of its contributors may be used to endorse or promote products
  derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL IVAAR BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]

local skills = {}

-- Weapon Skills with their corresponding skillchain properties
skills.weapon_skills = {
    [1] = {en='Combo',skillchain={'Impaction'}},
    [2] = {en='Shoulder Tackle',skillchain={'Reverberation','Impaction'}},
    [3] = {en='One Inch Punch',skillchain={'Compression'}},
    [4] = {en='Backhand Blow',skillchain={'Detonation'}},
    [5] = {en='Raging Fists',skillchain={'Impaction'}},
    [6] = {en='Spinning Attack',skillchain={'Liquefaction','Impaction'}},
    [7] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
    [8] = {en='Dragon Kick',skillchain={'Fragmentation'}},
    [9] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
    [10] = {en='Final Heaven',skillchain={'Light','Fusion'}},
    [11] = {en='Ascetic\'s Fury',skillchain={'Fusion','Transfixion'}},
    [12] = {en='Stringing Pummel',skillchain={'Gravitation','Liquefaction'}},
    [13] = {en='Tornado Kick',skillchain={'Induration','Detonation','Impaction'}},
    [14] = {en='Victory Smite',skillchain={'Light','Fragmentation'}},
    [15] = {en='Shijin Spiral',skillchain={'Fusion','Reverberation'},aeonic='Light',weapon='Godhand'},
    [16] = {en='Wasp Sting',skillchain={'Scission'}},
    [17] = {en='Viper Bite',skillchain={'Scission'}},
    [18] = {en='Shadowstitch',skillchain={'Reverberation'}},
    [19] = {en='Gust Slash',skillchain={'Detonation'}},
    [20] = {en='Cyclone',skillchain={'Detonation','Impaction'}},
    [23] = {en='Dancing Edge',skillchain={'Scission','Detonation'}},
    [24] = {en='Shark Bite',skillchain={'Fragmentation'}},
    [25] = {en='Evisceration',skillchain={'Gravitation','Transfixion'}},
    [26] = {en='Mercy Stroke',skillchain={'Darkness','Gravitation'}},
    [27] = {en='Mandalic Stab',skillchain={'Fusion','Compression'}},
    [28] = {en='Mordant Rime',skillchain={'Fragmentation','Distortion'}},
    [29] = {en='Pyrrhic Kleos',skillchain={'Distortion','Scission'}},
    [30] = {en='Aeolian Edge',skillchain={'Scission','Detonation','Impaction'}},
    [31] = {en='Rudra\'s Storm',skillchain={'Darkness','Distortion'}},
    [32] = {en='Fast Blade',skillchain={'Scission'}},
    [33] = {en='Burning Blade',skillchain={'Liquefaction'}},
    [34] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [35] = {en='Flat Blade',skillchain={'Impaction'}},
    [36] = {en='Shining Blade',skillchain={'Scission'}},
    [37] = {en='Seraph Blade',skillchain={'Scission'}},
    [38] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
    [40] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [41] = {en='Swift Blade',skillchain={'Gravitation'}},
    [42] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [43] = {en='Knights of Round',skillchain={'Light','Fusion'}},
    [44] = {en='Death Blossom',skillchain={'Fragmentation','Distortion'}},
    [45] = {en='Atonement',skillchain={'Fusion','Reverberation'}},
    [46] = {en='Expiacion',skillchain={'Distortion','Scission'}},
    [48] = {en='Hard Slash',skillchain={'Scission'}},
    [49] = {en='Power Slash',skillchain={'Transfixion'}},
    [50] = {en='Frostbite',skillchain={'Induration'}},
    [51] = {en='Freezebite',skillchain={'Induration','Detonation'}},
    [52] = {en='Shockwave',skillchain={'Reverberation'}},
    [53] = {en='Crescent Moon',skillchain={'Scission'}},
    [54] = {en='Sickle Moon',skillchain={'Scission','Impaction'}},
    [55] = {en='Spinning Slash',skillchain={'Fragmentation'}},
    [56] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
    [57] = {en='Scourge',skillchain={'Light','Fusion'}},
    [58] = {en='Herculean Slash',skillchain={'Induration','Detonation','Impaction'}},
    [59] = {en='Torcleaver',skillchain={'Light','Distortion'}},
    [60] = {en='Resolution',skillchain={'Fragmentation','Scission'},aeonic='Light',weapon='Lionheart'},
    [61] = {en='Dimidiation',skillchain={'Light','Fragmentation'}},
    [64] = {en='Raging Axe',skillchain={'Detonation','Impaction'}},
    [65] = {en='Smash Axe',skillchain={'Induration','Reverberation'}},
    [66] = {en='Gale Axe',skillchain={'Detonation'}},
    [67] = {en='Avalanche Axe',skillchain={'Scission','Impaction'}},
    [68] = {en='Spinning Axe',skillchain={'Liquefaction','Scission','Impaction'}},
    [69] = {en='Rampage',skillchain={'Scission'}},
    [70] = {en='Calamity',skillchain={'Scission','Impaction'}},
    [71] = {en='Mistral Axe',skillchain={'Fusion'}},
    [72] = {en='Decimation',skillchain={'Fusion','Reverberation'}},
    [73] = {en='Onslaught',skillchain={'Darkness','Gravitation'}},
    [74] = {en='Primal Rend',skillchain={'Gravitation','Reverberation'}},
    [75] = {en='Bora Axe',skillchain={'Scission','Detonation'}},
    [76] = {en='Cloudsplitter',skillchain={'Darkness','Fragmentation'}},
    [77] = {en='Ruinator',skillchain={'Distortion','Detonation'},aeonic='Darkness',weapon='Tri-Edge'},
    [80] = {en='Shield Break',skillchain={'Impaction'}},
    [81] = {en='Iron Tempest',skillchain={'Scission'}},
    [82] = {en='Sturmwind',skillchain={'Reverberation','Scission'}},
    [83] = {en='Armor Break',skillchain={'Impaction'}},
    [84] = {en='Keen Edge',skillchain={'Compression'}},
    [85] = {en='Weapon Break',skillchain={'Impaction'}},
    [86] = {en='Raging Rush',skillchain={'Induration','Reverberation'}},
    [87] = {en='Full Break',skillchain={'Distortion'}},
    [88] = {en='Steel Cyclone',skillchain={'Distortion','Detonation'}},
    [89] = {en='Metatron Torment',skillchain={'Light','Fusion'}},
    [90] = {en='King\'s Justice',skillchain={'Fragmentation','Scission'}},
    [91] = {en='Fell Cleave',skillchain={'Scission','Detonation','Impaction'}},
    [92] = {en='Ukko\'s Fury',skillchain={'Light','Fragmentation'}},
    [93] = {en='Upheaval',skillchain={'Fusion','Compression'},aeonic='Light',weapon='Chango'},
    [96] = {en='Slice',skillchain={'Scission'}},
    [97] = {en='Dark Harvest',skillchain={'Reverberation'}},
    [98] = {en='Shadow of Death',skillchain={'Induration','Reverberation'}},
    [99] = {en='Nightmare Scythe',skillchain={'Compression','Scission'}},
    [100] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
    [101] = {en='Vorpal Scythe',skillchain={'Transfixion','Scission'}},
    [102] = {en='Guillotine',skillchain={'Induration'}},
    [103] = {en='Cross Reaper',skillchain={'Distortion'}},
    [104] = {en='Spiral Hell',skillchain={'Distortion','Scission'}},
    [105] = {en='Catastrophe',skillchain={'Darkness','Gravitation'}},
    [106] = {en='Insurgency',skillchain={'Fusion','Compression'}},
    [107] = {en='Infernal Scythe',skillchain={'Compression','Reverberation'}},
    [108] = {en='Quietus',skillchain={'Darkness','Distortion'}},
    [109] = {en='Entropy',skillchain={'Gravitation','Reverberation'},aeonic='Darkness',weapon='Anguta'},
    [112] = {en='Double Thrust',skillchain={'Transfixion'}},
    [113] = {en='Thunder Thrust',skillchain={'Transfixion','Impaction'}},
    [114] = {en='Raiden Thrust',skillchain={'Transfixion','Impaction'}},
    [115] = {en='Leg Sweep',skillchain={'Impaction'}},
    [116] = {en='Penta Thrust',skillchain={'Compression'}},
    [117] = {en='Vorpal Thrust',skillchain={'Reverberation','Transfixion'}},
    [118] = {en='Skewer',skillchain={'Transfixion','Impaction'}},
    [119] = {en='Wheeling Thrust',skillchain={'Fusion'}},
    [120] = {en='Impulse Drive',skillchain={'Gravitation','Induration'}},
    [121] = {en='Geirskogul',skillchain={'Light','Distortion'}},
    [122] = {en='Drakesbane',skillchain={'Fusion','Transfixion'}},
    [123] = {en='Sonic Thrust',skillchain={'Transfixion','Scission'}},
    [124] = {en='Camlann\'s Torment',skillchain={'Light','Fragmentation'}},
    [125] = {en='Stardiver',skillchain={'Gravitation','Transfixion'},aeonic='Darkness',weapon='Trishula'},
    [128] = {en='Blade: Rin',skillchain={'Transfixion'}},
    [129] = {en='Blade: Retsu',skillchain={'Scission'}},
    [130] = {en='Blade: Teki',skillchain={'Reverberation'}},
    [131] = {en='Blade: To',skillchain={'Induration','Detonation'}},
    [132] = {en='Blade: Chi',skillchain={'Transfixion','Impaction'}},
    [133] = {en='Blade: Ei',skillchain={'Compression'}},
    [134] = {en='Blade: Jin',skillchain={'Detonation','Impaction'}},
    [135] = {en='Blade: Ten',skillchain={'Gravitation'}},
    [136] = {en='Blade: Ku',skillchain={'Gravitation','Transfixion'}},
    [137] = {en='Blade: Metsu',skillchain={'Darkness','Fragmentation'}},
    [138] = {en='Blade: Kamu',skillchain={'Fragmentation','Compression'}},
    [139] = {en='Blade: Yu',skillchain={'Reverberation','Scission'}},
    [140] = {en='Blade: Hi',skillchain={'Darkness','Gravitation'}},
    [141] = {en='Blade: Shun',skillchain={'Fusion','Impaction'},aeonic='Light',weapon='Heishi Shorinken'},
    [144] = {en='Tachi: Enpi',skillchain={'Transfixion','Scission'}},
    [145] = {en='Tachi: Hobaku',skillchain={'Induration'}},
    [146] = {en='Tachi: Goten',skillchain={'Transfixion','Impaction'}},
    [147] = {en='Tachi: Kagero',skillchain={'Liquefaction'}},
    [148] = {en='Tachi: Jinpu',skillchain={'Scission','Detonation'}},
    [149] = {en='Tachi: Koki',skillchain={'Reverberation','Impaction'}},
    [150] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
    [151] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
    [152] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [153] = {en='Tachi: Kaiten',skillchain={'Light','Fragmentation'}},
    [154] = {en='Tachi: Rana',skillchain={'Gravitation','Induration'}},
    [155] = {en='Tachi: Ageha',skillchain={'Compression','Scission'}},
    [156] = {en='Tachi: Fudo',skillchain={'Light','Distortion'}},
    [157] = {en='Tachi: Shoha',skillchain={'Fragmentation','Compression'},aeonic='Light',weapon='Dojikiri Yasutsuna'},
    [158] = {en='Tachi: Suikawari',skillchain={'Fusion'}},
    [160] = {en='Shining Strike',skillchain={'Impaction'}},
    [161] = {en='Seraph Strike',skillchain={'Impaction'}},
    [162] = {en='Brainshaker',skillchain={'Reverberation'}},
    [165] = {en='Skullbreaker',skillchain={'Induration','Reverberation'}},
    [166] = {en='True Strike',skillchain={'Detonation','Impaction'}},
    [167] = {en='Judgment',skillchain={'Impaction'}},
    [168] = {en='Hexa Strike',skillchain={'Fusion'}},
    [169] = {en='Black Halo',skillchain={'Fragmentation','Compression'}},
    [170] = {en='Randgrith',skillchain={'Light','Fragmentation'}},
    [172] = {en='Flash Nova',skillchain={'Induration','Reverberation'}},
    [174] = {en='Realmrazer',skillchain={'Fusion','Impaction'},aeonic='Light',weapon='Tishtrya'},
    [175] = {en='Exudation',skillchain={'Darkness','Fragmentation'}},
    [176] = {en='Heavy Swing',skillchain={'Impaction'}},
    [177] = {en='Rock Crusher',skillchain={'Impaction'}},
    [178] = {en='Earth Crusher',skillchain={'Detonation','Impaction'}},
    [179] = {en='Starburst',skillchain={'Compression','Reverberation'}},
    [180] = {en='Sunburst',skillchain={'Compression','Reverberation'}},
    [181] = {en='Shell Crusher',skillchain={'Detonation'}},
    [182] = {en='Full Swing',skillchain={'Liquefaction','Impaction'}},
    [184] = {en='Retribution',skillchain={'Gravitation','Reverberation'}},
    [185] = {en='Gate of Tartarus',skillchain={'Darkness','Distortion'}},
    [186] = {en='Vidohunir',skillchain={'Fragmentation','Distortion'}},
    [187] = {en='Garland of Bliss',skillchain={'Fusion','Reverberation'}},
    [188] = {en='Omniscience',skillchain={'Gravitation','Transfixion'}},
    [189] = {en='Cataclysm',skillchain={'Compression','Reverberation'}},
    [191] = {en='Shattersoul',skillchain={'Gravitation','Induration'},aeonic='Darkness',weapon='Khatvanga'},
    [192] = {en='Flaming Arrow',skillchain={'Liquefaction','Transfixion'}},
    [193] = {en='Piercing Arrow',skillchain={'Reverberation','Transfixion'}},
    [194] = {en='Dulling Arrow',skillchain={'Liquefaction','Transfixion'}},
    [196] = {en='Sidewinder',skillchain={'Reverberation','Transfixion','Detonation'}},
    [197] = {en='Blast Arrow',skillchain={'Induration','Transfixion'}},
    [198] = {en='Arching Arrow',skillchain={'Fusion'}},
    [199] = {en='Empyreal Arrow',skillchain={'Fusion','Transfixion'}},
    [200] = {en='Namas Arrow',skillchain={'Light','Distortion'}},
    [201] = {en='Refulgent Arrow',skillchain={'Reverberation','Transfixion'}},
    [202] = {en='Jishnu\'s Radiance',skillchain={'Light','Fusion'}},
    [203] = {en='Apex Arrow',skillchain={'Fragmentation','Transfixion'},aeonic='Light',weapon='Fail-Not'},
    [208] = {en='Hot Shot',skillchain={'Liquefaction','Transfixion'}},
    [209] = {en='Split Shot',skillchain={'Reverberation','Transfixion'}},
    [210] = {en='Sniper Shot',skillchain={'Liquefaction','Transfixion'}},
    [212] = {en='Slug Shot',skillchain={'Reverberation','Transfixion','Detonation'}},
    [213] = {en='Blast Shot',skillchain={'Induration','Transfixion'}},
    [214] = {en='Heavy Shot',skillchain={'Fusion'}},
    [215] = {en='Detonator',skillchain={'Fusion','Transfixion'}},
    [216] = {en='Coronach',skillchain={'Darkness','Fragmentation'}},
    [217] = {en='Trueflight',skillchain={'Fragmentation','Scission'}},
    [218] = {en='Leaden Salute',skillchain={'Gravitation','Transfixion'}},
    [219] = {en='Numbing Shot',skillchain={'Induration','Detonation','Impaction'}},
    [220] = {en='Wildfire',skillchain={'Darkness','Gravitation'}},
    [221] = {en='Last Stand',skillchain={'Fusion','Reverberation'},aeonic='Light',weapon='Fomalhaut'},
    [224] = {en='Exenterator',skillchain={'Fragmentation','Scission'},aeonic='Light',weapon='Aeneas'},
    [225] = {en='Chant du Cygne',skillchain={'Light','Distortion'}},
    [226] = {en='Requiescat',skillchain={'Gravitation','Scission'},aeonic='Darkness',weapon='Sequence'},
    [227] = {en='Knights of Rotund',skillchain={'Light'}},
    [228] = {en='Final Paradise',skillchain={'Light'}},
    [238] = {en='Uriel Blade',skillchain={'Light','Fragmentation'}},
    [239] = {en='Glory Slash',skillchain={'Light','Fusion'}},
}

-- BLU spells that are able to form a skillchain under the use of Chain Affinity
skills.blue_chain_spells = {
    [519] = {en='Screwdriver',skillchain={'Transfixion','Scission'}},
    [527] = {en='Smite of Rage',skillchain={'Detonation'}},
    [529] = {en='Bludgeon',skillchain={'Liquefaction'}},
    [539] = {en='Terror Touch',skillchain={'Compression','Reverberation'}},
    [540] = {en='Spinal Cleave',skillchain={'Scission','Detonation'}},
    [543] = {en='Mandibular Bite',skillchain={'Induration'}},
    [545] = {en='Sickle Slash',skillchain={'Compression'}},
    [551] = {en='Power Attack',skillchain={'Reverberation'}},
    [554] = {en='Death Scissors',skillchain={'Compression','Reverberation'}},
    [560] = {en='Frenetic Rip',skillchain={'Induration'}},
    [564] = {en='Body Slam',skillchain={'Impaction'}},
    [567] = {en='Helldive',skillchain={'Transfixion'}},
    [569] = {en='Jet Stream',skillchain={'Impaction'}},
    [577] = {en='Foot Kick',skillchain={'Detonation'}},
    [585] = {en='Ram Charge',skillchain={'Fragmentation'}},
    [587] = {en='Claw Cyclone',skillchain={'Scission'}},
    [589] = {en='Dimensional Death',skillchain={'Transfixion','Impaction'}},
    [594] = {en='Uppercut',skillchain={'Liquefaction','Impaction'}},
    [596] = {en='Pinecone Bomb',skillchain={'Liquefaction'}},
    [597] = {en='Sprout Smack',skillchain={'Reverberation'}},
    [599] = {en='Queasyshroom',skillchain={'Compression'}},
    [603] = {en='Wild Oats',skillchain={'Transfixion'}},
    [611] = {en='Disseverment',skillchain={'Distortion'}},
    [617] = {en='Vertical Cleave',skillchain={'Gravitation'}},
    [620] = {en='Battle Dance',skillchain={'Impaction'}},
    [622] = {en='Grand Slam',skillchain={'Induration'}},
    [623] = {en='Head Butt',skillchain={'Impaction'}},
    [628] = {en='Frypan',skillchain={'Impaction'}},
    [631] = {en='Hydro Shot',skillchain={'Reverberation'}},
    [638] = {en='Feather Storm',skillchain={'Transfixion'}},
    [640] = {en='Tail Slap',skillchain={'Reverberation'}},
    [641] = {en='Hysteric Barrage',skillchain={'Detonation'}},
    [643] = {en='Cannonball',skillchain={'Fusion'}},
    [650] = {en='Seedspray',skillchain={'Induration','Detonation'}},
    [652] = {en='Spiral Spin',skillchain={'Transfixion'}},
    [653] = {en='Asuran Claws',skillchain={'Liquefaction','Impaction'}},
    [654] = {en='Sub-zero Smash',skillchain={'Fragmentation'}},
    [665] = {en='Final Sting',skillchain={'Fusion'}},
    [666] = {en='Goblin Rush',skillchain={'Fusion','Impaction'}},
    [667] = {en='Vanity Dive',skillchain={'Transfixion','Scission'}},
    [669] = {en='Whirl of Rage',skillchain={'Scission','Detonation'}},
    [670] = {en='Benthic Typhoon',skillchain={'Gravitation','Transfixion'}},
    [673] = {en='Quad. Continuum',skillchain={'Distortion','Scission'}},
    [677] = {en='Empty Thrash',skillchain={'Compression','Scission'}},
    [682] = {en='Delta Thrust',skillchain={'Liquefaction','Detonation'}},
    [688] = {en='Heavy Strike',skillchain={'Fragmentation','Transfixion'}},
    [692] = {en='Sudden Lunge',skillchain={'Detonation'}},
    [693] = {en='Quadrastrike',skillchain={'Liquefaction','Scission','Impaction'}},
    [697] = {en='Amorphic Spikes',skillchain={'Gravitation'}},
    [699] = {en='Barbed Crescent',skillchain={'Distortion','Scission'}},
    [704] = {en='Paralyzing Triad',skillchain={'Gravitation'}},
    [706] = {en='Glutinous Dart',skillchain={'Fragmentation'}},
    [709] = {en='Thrashing Assault',skillchain={'Fusion'}},
    [714] = {en='Sinker Drill',skillchain={'Gravitation','Reverberation'}},
    [723] = {en='Saurian Slide',skillchain={'Fragmentation','Distortion'}},
    [740] = {en='Tourbillion',skillchain={'Light','Fragmentation'}},
    [742] = {en='Bilgestorm',skillchain={'Darkness','Gravitation'}},
    [743] = {en='Bloodrake',skillchain={'Darkness','Distortion'}},
}

-- BLU Spells that are able to magic burst when Burst Affinity is active
skills.blue_burst_spells = {
	[513] = {en='Venom Shell',element={'Water'}},
    [515] = {en='Maelstrom',element={'Water'}},
    [521] = {en='MP Drainkiss',element={'Dark'}},
    [522] = {en='Death Ray',element={'Dark'}},
    [524] = {en='Sandspin',element={'Earth'}},
    [531] = {en='Ice Break',element={'Ice'}},
    [532] = {en='Blitzstrahl',element={'Lightning'}},
    [533] = {en='Self-Destruct',element={'Fire'}},
    [534] = {en='Mysterious Light',element={'Wind'}},
    [535] = {en='Cold Wave',element={'Ice'}},
    [536] = {en='Poison Breath',element={'Water'}},
    [537] = {en='Stinking Gas',element={'Wind'}},
    [541] = {en='Blood Saber',element={'Dark'}},
    [542] = {en='Digest',element={'Dark'}},
    [544] = {en='Cursed Sphere',element={'Water'}},
    [548] = {en='Filamented Hold',element={'Earth'}},
    [555] = {en='Magnetite Cloud',element={'Earth'}},
    [557] = {en='Eyes On Me',element={'Dark'}},
    [561] = {en='Frightful Roar',element={'Wind'}},
    [563] = {en='Hecatomb Wave',element={'Wind'}},
    [565] = {en='Radiant Breath',element={'Light'}},
    [570] = {en='Blood Drain',element={'Dark'}},
    [572] = {en='Sound Blast',element={'Fire'}},
    [573] = {en='Feather Tickle',element={'Wind'}},
    [575] = {en='Jettatura',element={'Dark'}},
    [576] = {en='Yawn',element={'Light'}},
    [579] = {en='Voracious Trunk',element={'Wind'}},
    [582] = {en='Chaotic Eye',element={'Wind'}},
    [584] = {en='Sheep Song',element={'Light'}},
    [588] = {en='Lowing',element={'Fire'}},
    [591] = {en='Heat Breath',element={'Fire'}},
    [592] = {en='Blank Gaze',element={'Light'}},
    [595] = {en='1000 Needles',element={'Light'}},
    [598] = {en='Soporific',element={'Dark'}},
    [604] = {en='Bad Breath',element={'Earth'}},
    [605] = {en='Geist Wall',element={'Dark'}},
    [606] = {en='Awful Eye',element={'Water'}},
    [608] = {en='Frost Breath',element={'Ice'}},
    [610] = {en='Infrasonics',element={'Ice'}},
    [612] = {en='Actinic Burst',element={'Light'}},
    [616] = {en='Temporal Shift',element={'Lightning'}},
    [618] = {en='Blastbomb',element={'Fire'}},
    [621] = {en='Sandspray',element={'Dark'}},
    [626] = {en='Bomb Toss',element={'Fire'}},
    [629] = {en='Flying Hip Press',element={'Wind'}},
    [633] = {en='Enervation',element={'Dark'}},
    [634] = {en='Light of Penance',element={'Light'}},
    [637] = {en='Firespit',element={'Fire'}},
    [644] = {en='Mind Blast',element={'Lightning'}},
    [646] = {en='Magic Hammer',element={'Light'}},
    [648] = {en='Regurgitation',element={'Water'}},
    [651] = {en='Corrosive Ooze',element={'Water'}},
    [656] = {en='Acrid Stream',element={'Water'}},
    [657] = {en='Blazing Bound',element={'Fire'}},
    [659] = {en='Demoralizing Roar',element={'Water'}},
    [660] = {en='Cimicine Discharge',element={'Earth'}},
    [663] = {en='Leafstorm',element={'Wind'}},
    [671] = {en='Auroral Drape',element={'Wind'}},
    [672] = {en='Osmosis',element={'Dark'}},
    [675] = {en='Thermal Pulse',element={'Fire'}},
    [678] = {en='Dream Flower',element={'Dark'}},
    [680] = {en='Charged Whisker',element={'Lightning'}},
    [683] = {en='Evryone. Grudge',element={'Dark'}},
    [684] = {en='Reaving Wind',element={'Wind'}},
    [686] = {en='Mortal Ray',element={'Dark'}},
    [687] = {en='Water Bomb',element={'Water'}},
    [689] = {en='Dark Orb',element={'Dark'}},
    [694] = {en='Vapor Spray',element={'Water'}},
    [695] = {en='Thunder Breath',element={'Lightning'}},
    [698] = {en='Wind Breath',element={'Wind'}},
    [701] = {en='Tem. Upheaval',element={'Wind'}},
    [702] = {en='Rending Deluge',element={'Water'}},
    [703] = {en='Embalming Earth',element={'Earth'}},
    [705] = {en='Foul Waters',element={'Water'}},
    [707] = {en='Retinal Glare',element={'Light'}},
    [708] = {en='Subduction',element={'Wind'}},
    [712] = {en='Rail Cannon',element={'Light'}},
    [713] = {en='Diffusion Ray',element={'Light'}},
    [715] = {en='Molting Plumage',element={'Wind'}},
    [716] = {en='Nectarous Deluge',element={'Water'}},
    [718] = {en='Atra. Libations',element={'Dark'}},
    [719] = {en='Searing Tempest',element={'Fire'}},
    [720] = {en='Spectral Floe',element={'Ice'}},
    [721] = {en='Anvil Lightning',element={'Lightning'}},
    [722] = {en='Entomb',element={'Earth'}},
    [724] = {en='Palling Salvo',element={'Dark'}},
    [725] = {en='Blinding Fulgor',element={'Light'}},
    [726] = {en='Scouring Spate',element={'Water'}},
    [727] = {en='Silent Storm',element={'Wind'}},
    [728] = {en='Tenebral Crush',element={'Dark'}},
    [736] = {en='Thunderbolt',element={'Lightning'}},
    [738] = {en='Absolute Terror',element={'Dark'}},
    [739] = {en='Gates of Hades',element={'Fire'}},
    [744] = {en='Droning Whirlwind',element={'Wind'}},
    [746] = {en='Blistering Roar',element={'Dark'}},
    [747] = {en='Uproot',element={'Light'}},
    [748] = {en='Crashing Thunder',element={'Lightning'}},
    [749] = {en='Polar Roar',element={'Ice'}},
    [751] = {en='Cruel Joke',element={'Dark'}},
    [752] = {en='Cesspool',element={'Water'}},
    [753] = {en='Tearing Gust',element={'Wind'}},
}

-- Regular spells with Magic Burst properties
skills.spells = {
	[1] = {en='Cure',element={'Light'}},
    [2] = {en='Cure II',element={'Light'}},
    [3] = {en='Cure III',element={'Light'}},
    [4] = {en='Cure IV',element={'Light'}},
    [5] = {en='Cure V',element={'Light'}},
    [6] = {en='Cure VI',element={'Light'}},
	[21] = {en='Holy',element={'Light'}},
    [22] = {en='Holy II',element={'Light'}},
    [23] = {en='Dia',element={'Light'}},
    [24] = {en='Dia II',element={'Light'}},
    [25] = {en='Dia III',element={'Light'}},
    [26] = {en='Dia IV',element={'Light'}},
    [27] = {en='Dia V',element={'Light'}},
    [28] = {en='Banish',element={'Light'}},
    [29] = {en='Banish II',element={'Light'}},
    [30] = {en='Banish III',element={'Light'}},
    [31] = {en='Banish IV',element={'Light'}},
    [32] = {en='Banish V',element={'Light'}},
    [33] = {en='Diaga',element={'Light'}},
    [34] = {en='Diaga II',element={'Light'}},
    [35] = {en='Diaga III',element={'Light'}},
    [36] = {en='Diaga IV',element={'Light'}},
    [37] = {en='Diaga V',element={'Light'}},
    [38] = {en='Banishga',element={'Light'}},
    [39] = {en='Banishga II',element={'Light'}},
    [40] = {en='Banishga III',element={'Light'}},
    [41] = {en='Banishga IV',element={'Light'}},
    [42] = {en='Banishga V',element={'Light'}},
    [56] = {en='Slow',element={'Earth'}},
    [58] = {en='Paralyze',element={'Ice'}},
	[59] = {en='Silence',element={'Wind'}},
    [79] = {en='Slow II',element={'Earth'}},
    [80] = {en='Paralyze II',element={'Ice'}},
    [98] = {en='Repose',element={'Light'}},
    [112] = {en='Flash',element={'Light'}},
    [144] = {en='Fire',element={'Fire'}},
    [145] = {en='Fire II',element={'Fire'}},
    [146] = {en='Fire III',element={'Fire'}},
    [147] = {en='Fire IV',element={'Fire'}},
    [148] = {en='Fire V',element={'Fire'}},
    [149] = {en='Blizzard',element={'Ice'}},
    [150] = {en='Blizzard II',element={'Ice'}},
    [151] = {en='Blizzard III',element={'Ice'}},
    [152] = {en='Blizzard IV',element={'Ice'}},
    [153] = {en='Blizzard V',element={'Ice'}},
    [154] = {en='Aero',element={'Wind'}},
    [155] = {en='Aero II',element={'Wind'}},
    [156] = {en='Aero III',element={'Wind'}},
    [157] = {en='Aero IV',element={'Wind'}},
    [158] = {en='Aero V',element={'Wind'}},
    [159] = {en='Stone',element={'Earth'}},
    [160] = {en='Stone II',element={'Earth'}},
    [161] = {en='Stone III',element={'Earth'}},
    [162] = {en='Stone IV',element={'Earth'}},
    [163] = {en='Stone V',element={'Earth'}},
    [164] = {en='Thunder',element={'Lightning'}},
    [165] = {en='Thunder II',element={'Lightning'}},
    [166] = {en='Thunder III',element={'Lightning'}},
    [167] = {en='Thunder IV',element={'Lightning'}},
    [168] = {en='Thunder V',element={'Lightning'}},
    [169] = {en='Water',element={'Water'}},
    [170] = {en='Water II',element={'Water'}},
    [171] = {en='Water III',element={'Water'}},
    [172] = {en='Water IV',element={'Water'}},
    [173] = {en='Water V',element={'Water'}},
    [174] = {en='Firaga',element={'Fire'}},
    [175] = {en='Firaga II',element={'Fire'}},
    [176] = {en='Firaga III',element={'Fire'}},
    [177] = {en='Firaga IV',element={'Fire'}},
    [178] = {en='Firaga V',element={'Fire'}},
    [179] = {en='Blizzaga',element={'Ice'}},
    [180] = {en='Blizzaga II',element={'Ice'}},
    [181] = {en='Blizzaga III',element={'Ice'}},
    [182] = {en='Blizzaga IV',element={'Ice'}},
    [183] = {en='Blizzaga V',element={'Ice'}},
    [184] = {en='Aeroga',element={'Wind'}},
    [185] = {en='Aeroga II',element={'Wind'}},
    [186] = {en='Aeroga III',element={'Wind'}},
    [187] = {en='Aeroga IV',element={'Wind'}},
    [188] = {en='Aeroga V',element={'Wind'}},
    [189] = {en='Stonega',element={'Earth'}},
    [190] = {en='Stonega II',element={'Earth'}},
    [191] = {en='Stonega III',element={'Earth'}},
    [192] = {en='Stonega IV',element={'Earth'}},
    [193] = {en='Stonega V',element={'Earth'}},
    [194] = {en='Thundaga',element={'Lightning'}},
    [195] = {en='Thundaga II',element={'Lightning'}},
    [196] = {en='Thundaga III',element={'Lightning'}},
    [197] = {en='Thundaga IV',element={'Lightning'}},
    [198] = {en='Thundaga V',element={'Lightning'}},
    [199] = {en='Waterga',element={'Water'}},
    [200] = {en='Waterga II',element={'Water'}},
    [201] = {en='Waterga III',element={'Water'}},
    [202] = {en='Waterga IV',element={'Water'}},
    [203] = {en='Waterga V',element={'Water'}},
    [204] = {en='Flare',element={'Fire'}},
    [205] = {en='Flare II',element={'Fire'}},
    [206] = {en='Freeze',element={'Ice'}},
    [207] = {en='Freeze II',element={'Ice'}},
    [208] = {en='Tornado',element={'Wind'}},
    [209] = {en='Tornado II',element={'Wind'}},
    [210] = {en='Quake',element={'Earth'}},
    [211] = {en='Quake II',element={'Earth'}},
    [212] = {en='Burst',element={'Lightning'}},
    [213] = {en='Burst II',element={'Lightning'}},
    [214] = {en='Flood',element={'Water'}},
    [215] = {en='Flood II',element={'Water'}},
    [216] = {en='Gravity',element={'Wind'}},
    [217] = {en='Gravity II',element={'Wind'}},
    [219] = {en='Comet',element={'Dark'}},
    [220] = {en='Poison',element={'Water'}},
    [221] = {en='Poison II',element={'Water'}},
    [222] = {en='Poison III',element={'Water'}},
    [223] = {en='Poison IV',element={'Water'}},
    [224] = {en='Poison V',element={'Water'}},
    [225] = {en='Poisonga',element={'Water'}},
    [226] = {en='Poisonga II',element={'Water'}},
    [227] = {en='Poisonga III',element={'Water'}},
    [228] = {en='Poisonga IV',element={'Water'}},
    [229] = {en='Poisonga V',element={'Water'}},
    [230] = {en='Bio',element={'Dark'}},
    [231] = {en='Bio II',element={'Dark'}},
    [232] = {en='Bio III',element={'Dark'}},
    [233] = {en='Bio IV',element={'Dark'}},
    [234] = {en='Bio V',element={'Dark'}},
    [235] = {en='Burn',element={'Fire'}},
    [236] = {en='Frost',element={'Ice'}},
    [237] = {en='Choke',element={'Wind'}},
    [238] = {en='Rasp',element={'Earth'}},
    [239] = {en='Shock',element={'Lightning'}},
    [240] = {en='Drown',element={'Water'}},
    [242] = {en='Absorb-ACC',element={'Dark'}},
    [243] = {en='Absorb-Attri',element={'Dark'}},
    [245] = {en='Drain',element={'Dark'}},
    [246] = {en='Drain II',element={'Dark'}},
    [247] = {en='Aspir',element={'Dark'}},
    [248] = {en='Aspir II',element={'Dark'}},
    [252] = {en='Stun',element={'Lightning'}},
    [253] = {en='Sleep',element={'Dark'}},
    [254] = {en='Blind',element={'Dark'}},
    [255] = {en='Break',element={'Earth'}},
    [256] = {en='Virus',element={'Dark'}},
    [257] = {en='Curse',element={'Dark'}},
    [258] = {en='Bind',element={'Ice'}},
    [259] = {en='Sleep II',element={'Dark'}},
    [260] = {en='Dispel',element={'Dark'}},
    [266] = {en='Absorb-STR',element={'Dark'}},
    [267] = {en='Absorb-DEX',element={'Dark'}},
    [268] = {en='Absorb-VIT',element={'Dark'}},
    [269] = {en='Absorb-AGI',element={'Dark'}},
    [270] = {en='Absorb-INT',element={'Dark'}},
    [271] = {en='Absorb-MND',element={'Dark'}},
    [272] = {en='Absorb-CHR',element={'Dark'}},
    [273] = {en='Sleepga',element={'Dark'}},
    [274] = {en='Sleepga II',element={'Dark'}},
    [275] = {en='Absorb-TP',element={'Dark'}},
    [276] = {en='Blind II',element={'Dark'}},
    [278] = {en='Geohelix',element={'Earth'}},
    [279] = {en='Hydrohelix',element={'Water'}},
    [280] = {en='Anemohelix',element={'Wind'}},
    [281] = {en='Pyrohelix',element={'Fire'}},
    [282] = {en='Cryohelix',element={'Ice'}},
    [283] = {en='Ionohelix',element={'Lightning'}},
    [284] = {en='Noctohelix',element={'Dark'}},
    [285] = {en='Luminohelix',element={'Light'}},
	[286] = {en='Addle',element={'Fire'}},
    [319] = {en='Aisha: Ichi',element={'Water'}},
    [320] = {en='Katon: Ichi',element={'Fire'}},
    [321] = {en='Katon: Ni',element={'Fire'}},
    [322] = {en='Katon: San',element={'Fire'}},
    [323] = {en='Hyoton: Ichi',element={'Ice'}},
    [324] = {en='Hyoton: Ni',element={'Ice'}},
    [325] = {en='Hyoton: San',element={'Ice'}},
    [326] = {en='Huton: Ichi',element={'Wind'}},
    [327] = {en='Huton: Ni',element={'Wind'}},
    [328] = {en='Huton: San',element={'Wind'}},
    [329] = {en='Doton: Ichi',element={'Earth'}},
    [330] = {en='Doton: Ni',element={'Earth'}},
    [331] = {en='Doton: San',element={'Earth'}},
    [332] = {en='Raiton: Ichi',element={'Lightning'}},
    [333] = {en='Raiton: Ni',element={'Lightning'}},
    [334] = {en='Raiton: San',element={'Lightning'}},
    [335] = {en='Suiton: Ichi',element={'Water'}},
    [336] = {en='Suiton: Ni',element={'Water'}},
    [337] = {en='Suiton: San',element={'Water'}},
    [341] = {en='Jubaku: Ichi',element={'Ice'}},
    [342] = {en='Jubaku: Ni',element={'Ice'}},
    [343] = {en='Jubaku: San',element={'Ice'}},
    [344] = {en='Hojo: Ichi',element={'Earth'}},
    [345] = {en='Hojo: Ni',element={'Earth'}},
    [346] = {en='Hojo: San',element={'Earth'}},
    [347] = {en='Kurayami: Ichi',element={'Dark'}},
    [348] = {en='Kurayami: Ni',element={'Dark'}},
    [349] = {en='Kurayami: San',element={'Dark'}},
    [350] = {en='Dokumori: Ichi',element={'Water'}},
    [351] = {en='Dokumori: Ni',element={'Water'}},
    [352] = {en='Dokumori: San',element={'Water'}},
    [356] = {en='Paralyga',element={'Ice'}},
    [357] = {en='Slowga',element={'Earth'}},
    [359] = {en='Silencega',element={'Wind'}},
    [360] = {en='Dispelga',element={'Dark'}},
    [361] = {en='Blindga',element={'Dark'}},
    [362] = {en='Bindga',element={'Ice'}},
    [363] = {en='Sleepga',element={'Dark'}},
    [364] = {en='Sleepga II',element={'Dark'}},
    [365] = {en='Breakga',element={'Earth'}},
    [366] = {en='Graviga',element={'Wind'}},
    [367] = {en='Death',element={'Dark'}},
    [368] = {en='Foe Requiem',element={'Light'}},
    [369] = {en='Foe Requiem II',element={'Light'}},
    [370] = {en='Foe Requiem III',element={'Light'}},
    [371] = {en='Foe Requiem IV',element={'Light'}},
    [372] = {en='Foe Requiem V',element={'Light'}},
    [373] = {en='Foe Requiem VI',element={'Light'}},
    [374] = {en='Foe Requiem VII',element={'Light'}},
    [375] = {en='Foe Requiem VIII',element={'Light'}},
    [376] = {en='Horde Lullaby',element={'Light'}},
    [377] = {en='Horde Lullaby II',element={'Light'}},
    [421] = {en='Battlefield Elegy',element={'Earth'}},
    [422] = {en='Carnage Elegy',element={'Earth'}},
    [423] = {en='Massacre Elegy',element={'Earth'}},
    [454] = {en='Fire Threnody',element={'Water'}},
    [455] = {en='Ice Threnody',element={'Fire'}},
    [456] = {en='Wind Threnody',element={'Ice'}},
    [457] = {en='Earth Threnody',element={'Wind'}},
    [458] = {en='Ltng. Threnody',element={'Earth'}},
    [459] = {en='Water Threnody',element={'Lightning'}},
    [460] = {en='Light Threnody',element={'Dark'}},
    [461] = {en='Dark Threnody',element={'Light'}},
    [462] = {en='Magic Finale',element={'Light'}},
    [463] = {en='Foe Lullaby',element={'Light'}},
    [466] = {en='Maiden\'s Virelai',element={'Light'}},
    [471] = {en='Foe Lullaby II',element={'Light'}},
    [472] = {en='Pining Nocturne',element={'Fire'}},
    [496] = {en='Firaja',element={'Fire'}},
    [497] = {en='Blizzaja',element={'Ice'}},
    [498] = {en='Aeroja',element={'Wind'}},
    [499] = {en='Stoneja',element={'Earth'}},
    [500] = {en='Thundaja',element={'Lightning'}},
    [501] = {en='Waterja',element={'Water'}},
    [502] = {en='Kaustra',element={'Dark'}},
    [503] = {en='Impact',element={'Dark'}},
    [508] = {en='Yurin: Ichi',element={'Dark'}},
    [828] = {en='Fira',element={'Fire'}},
    [829] = {en='Fira II',element={'Fire'}},
    [830] = {en='Blizzara',element={'Ice'}},
    [831] = {en='Blizzara II',element={'Ice'}},
    [832] = {en='Aera',element={'Wind'}},
    [833] = {en='Aera II',element={'Wind'}},
    [834] = {en='Stonera',element={'Earth'}},
    [835] = {en='Stonera II',element={'Earth'}},
    [836] = {en='Thundara',element={'Lightning'}},
    [837] = {en='Thundara II',element={'Lightning'}},
    [838] = {en='Watera',element={'Water'}},
    [839] = {en='Watera II',element={'Water'}},
    [841] = {en='Distract',element={'Ice'}},
    [842] = {en='Distract II',element={'Ice'}},
    [843] = {en='Frazzle',element={'Dark'}},
    [844] = {en='Frazzle II',element={'Dark'}},
    [849] = {en='Fire VI',element={'Fire'}},
    [850] = {en='Blizzard VI',element={'Ice'}},
    [851] = {en='Aero VI',element={'Wind'}},
    [852] = {en='Stone VI',element={'Earth'}},
    [853] = {en='Thunder VI',element={'Lightning'}},
    [854] = {en='Water VI',element={'Water'}},
    [865] = {en='Fira III',element={'Fire'}},
    [866] = {en='Blizzara III',element={'Ice'}},
    [867] = {en='Aera III',element={'Wind'}},
    [868] = {en='Stonera III',element={'Earth'}},
    [869] = {en='Thundara III',element={'Lightning'}},
    [870] = {en='Watera III',element={'Water'}},
    [871] = {en='Fire Threnody II',element={'Water'}},
    [872] = {en='Ice Threnody II',element={'Fire'}},
    [873] = {en='Wind Threnody II',element={'Ice'}},
    [874] = {en='Earth Threnody II',element={'Wind'}},
    [875] = {en='Ltng. Threnody II',element={'Earth'}},
    [876] = {en='Water Threnody II',element={'Lightning'}},
    [877] = {en='Light Threnody II',element={'Dark'}},
    [878] = {en='Dark Threnody II',element={'Light'}},
    [879] = {en='Inundation',element={'Light'}},
    [880] = {en='Drain III',element={'Dark'}},
    [881] = {en='Aspir III',element={'Dark'}},
    [882] = {en='Distract III',element={'Ice'}},
    [883] = {en='Frazzle III',element={'Dark'}},
    [884] = {en='Addle II',element={'Fire'}},
    [885] = {en='Geohelix II',element={'Earth'}},
    [886] = {en='Hydrohelix II',element={'Water'}},
    [887] = {en='Anemohelix II',element={'Wind'}},
    [888] = {en='Pyrohelix II',element={'Fire'}},
    [889] = {en='Cryohelix II',element={'Ice'}},
    [890] = {en='Ionohelix II',element={'Lightning'}},
    [891] = {en='Noctohelix II',element={'Dark'}},
    [892] = {en='Luminohelix II',element={'Light'}},
    [893] = {en='Full Cure',element={'Light'}},
}

-- Spells that are able to form a Skillchain under the use of Immanence (SCH)
skills.immanence_spells = {
	[144] = {en='Fire',skillchain={'Liquefaction'}},
    [145] = {en='Fire II',skillchain={'Liquefaction'}},
    [146] = {en='Fire III',skillchain={'Liquefaction'}},
    [147] = {en='Fire IV',skillchain={'Liquefaction'}},
    [148] = {en='Fire V',skillchain={'Liquefaction'}},
    [149] = {en='Blizzard',skillchain={'Induration'}},
    [150] = {en='Blizzard II',skillchain={'Induration'}},
    [151] = {en='Blizzard III',skillchain={'Induration'}},
    [152] = {en='Blizzard IV',skillchain={'Induration'}},
    [153] = {en='Blizzard V',skillchain={'Induration'}},
    [154] = {en='Aero',skillchain={'Detonation'}},
    [155] = {en='Aero II',skillchain={'Detonation'}},
    [156] = {en='Aero III',skillchain={'Detonation'}},
    [157] = {en='Aero IV',skillchain={'Detonation'}},
    [158] = {en='Aero V',skillchain={'Detonation'}},
    [159] = {en='Stone',skillchain={'Scission'}},
    [160] = {en='Stone II',skillchain={'Scission'}},
    [161] = {en='Stone III',skillchain={'Scission'}},
    [162] = {en='Stone IV',skillchain={'Scission'}},
    [163] = {en='Stone V',skillchain={'Scission'}},
    [164] = {en='Thunder',skillchain={'Impaction'}},
    [165] = {en='Thunder II',skillchain={'Impaction'}},
    [166] = {en='Thunder III',skillchain={'Impaction'}},
    [167] = {en='Thunder IV',skillchain={'Impaction'}},
    [168] = {en='Thunder V',skillchain={'Impaction'}},
    [169] = {en='Water',skillchain={'Reverberation'}},
    [170] = {en='Water II',skillchain={'Reverberation'}},
    [171] = {en='Water III',skillchain={'Reverberation'}},
    [172] = {en='Water IV',skillchain={'Reverberation'}},
    [173] = {en='Water V',skillchain={'Reverberation'}},
    [174] = {en='Firaga',skillchain={'Liquefaction'}},
    [175] = {en='Firaga II',skillchain={'Liquefaction'}},
    [176] = {en='Firaga III',skillchain={'Liquefaction'}},
    [177] = {en='Firaga IV',skillchain={'Liquefaction'}},
    [178] = {en='Firaga V',skillchain={'Liquefaction'}},
    [179] = {en='Blizzaga',skillchain={'Induration'}},
    [180] = {en='Blizzaga II',skillchain={'Induration'}},
    [181] = {en='Blizzaga III',skillchain={'Induration'}},
    [182] = {en='Blizzaga IV',skillchain={'Induration'}},
    [183] = {en='Blizzaga V',skillchain={'Induration'}},
    [184] = {en='Aeroga',skillchain={'Detonation'}},
    [185] = {en='Aeroga II',skillchain={'Detonation'}},
    [186] = {en='Aeroga III',skillchain={'Detonation'}},
    [187] = {en='Aeroga IV',skillchain={'Detonation'}},
    [188] = {en='Aeroga V',skillchain={'Detonation'}},
    [189] = {en='Stonega',skillchain={'Scission'}},
    [190] = {en='Stonega II',skillchain={'Scission'}},
    [191] = {en='Stonega III',skillchain={'Scission'}},
    [192] = {en='Stonega IV',skillchain={'Scission'}},
    [193] = {en='Stonega V',skillchain={'Scission'}},
    [194] = {en='Thundaga',skillchain={'Impaction'}},
    [195] = {en='Thundaga II',skillchain={'Impaction'}},
    [196] = {en='Thundaga III',skillchain={'Impaction'}},
    [197] = {en='Thundaga IV',skillchain={'Impaction'}},
    [198] = {en='Thundaga V',skillchain={'Impaction'}},
    [199] = {en='Waterga',skillchain={'Reverberation'}},
    [200] = {en='Waterga II',skillchain={'Reverberation'}},
    [201] = {en='Waterga III',skillchain={'Reverberation'}},
    [202] = {en='Waterga IV',skillchain={'Reverberation'}},
    [203] = {en='Waterga V',skillchain={'Reverberation'}},
    [204] = {en='Flare',skillchain={'Liquefaction'}},
    [205] = {en='Flare II',skillchain={'Liquefaction'}},
    [206] = {en='Freeze',skillchain={'Induration'}},
    [207] = {en='Freeze II',skillchain={'Induration'}},
    [208] = {en='Tornado',skillchain={'Detonation'}},
    [209] = {en='Tornado II',skillchain={'Detonation'}},
    [210] = {en='Quake',skillchain={'Scission'}},
    [211] = {en='Quake II',skillchain={'Scission'}},
    [212] = {en='Burst',skillchain={'Impaction'}},
    [213] = {en='Burst II',skillchain={'Impaction'}},
    [214] = {en='Flood',skillchain={'Reverberation'}},
    [215] = {en='Flood II',skillchain={'Reverberation'}},
	[219] = {en='Comet',skillchain={'Compression'}},
	[235] = {en='Burn',skillchain={'Liquefaction'}},
    [236] = {en='Frost',skillchain={'Induration'}},
    [237] = {en='Choke',skillchain={'Detonation'}},
    [238] = {en='Rasp',skillchain={'Scission'}},
    [239] = {en='Shock',skillchain={'Impaction'}},
    [240] = {en='Drown',skillchain={'Reverberation'}},
	[278] = {en='Geohelix',skillchain={'Scission'}},
    [279] = {en='Hydrohelix',skillchain={'Reverberation'}},
    [280] = {en='Anemohelix',skillchain={'Detonation'}},
    [281] = {en='Pyrohelix',skillchain={'Liquefaction'}},
    [282] = {en='Cryohelix',skillchain={'Induration'}},
    [283] = {en='Ionohelix',skillchain={'Impaction'}},
    [284] = {en='Noctohelix',skillchain={'Compression'}},
    [285] = {en='Luminohelix',skillchain={'Transfixion'}},
	[496] = {en='Firaja',skillchain={'Liquefaction'}},
    [497] = {en='Blizzaja',skillchain={'Induration'}},
    [498] = {en='Aeroja',skillchain={'Detonation'}},
    [499] = {en='Stoneja',skillchain={'Scission'}},
    [500] = {en='Thundaja',skillchain={'Impaction'}},
    [501] = {en='Waterja',skillchain={'Reverberation'}},
	[503] = {en='Impact',skillchain={'Compression'}},
	[828] = {en='Fira',skillchain={'Liquefaction'}},
    [829] = {en='Fira II',skillchain={'Liquefaction'}},
    [830] = {en='Blizzara',skillchain={'Induration'}},
    [831] = {en='Blizzara II',skillchain={'Induration'}},
    [832] = {en='Aera',skillchain={'Detonation'}},
    [833] = {en='Aera II',skillchain={'Detonation'}},
    [834] = {en='Stonera',skillchain={'Scission'}},
    [835] = {en='Stonera II',skillchain={'Scission'}},
    [836] = {en='Thundara',skillchain={'Impaction'}},
    [837] = {en='Thundara II',skillchain={'Impaction'}},
    [838] = {en='Watera',skillchain={'Reverberation'}},
    [839] = {en='Watera II',skillchain={'Reverberation'}},
	[849] = {en='Fire VI',skillchain={'Liquefaction'}},
    [850] = {en='Blizzard VI',skillchain={'Induration'}},
    [851] = {en='Aero VI',skillchain={'Detonation'}},
    [852] = {en='Stone VI',skillchain={'Scission'}},
    [853] = {en='Thunder VI',skillchain={'Impaction'}},
    [854] = {en='Water VI',skillchain={'Reverberation'}},
    [865] = {en='Fira III',skillchain={'Liquefaction'}},
    [866] = {en='Blizzara III',skillchain={'Induration'}},
    [867] = {en='Aera III',skillchain={'Detonation'}},
    [868] = {en='Stonera III',skillchain={'Scission'}},
    [869] = {en='Thundara III',skillchain={'Impaction'}},
    [870] = {en='Watera III',skillchain={'Reverberation'}},
	[885] = {en='Geohelix II',skillchain={'Scission'}},
    [886] = {en='Hydrohelix II',skillchain={'Reverberation'}},
    [887] = {en='Anemohelix II',skillchain={'Detonation'}},
    [888] = {en='Pyrohelix II',skillchain={'Liquefaction'}},
    [889] = {en='Cryohelix II',skillchain={'Induration'}},
    [890] = {en='Ionohelix II',skillchain={'Impaction'}},
    [891] = {en='Noctohelix II',skillchain={'Compression'}},
    [892] = {en='Luminohelix II',skillchain={'Transfixion'}},
}

-- BST Pet abilities that are able to form a Skillchain
-- TODO: Actually use this!
skills.monster_abilities = {
    [829] = {en='Great Wheel',skillchain={'Fragmentation','Scission'}},
    [830] = {en='Light Blade',skillchain={'Light','Fusion'}},
    [838] = {en='Howling Moon',skillchain={'Darkness','Distortion'}},
    [839] = {en='Howling Moon',skillchain={'Darkness','Distortion'}},
    [938] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
    [939] = {en='Swift Blade',skillchain={'Gravitation'}},
    [940] = {en='Rampage',skillchain={'Scission'}},
    [941] = {en='Calamity',skillchain={'Scission','Impaction'}},
    [943] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [944] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
    [945] = {en='Guillotine',skillchain={'Induration'}},
    [946] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
    [947] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
    [948] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [951] = {en='Hurricane Wing',skillchain={'Scission','Detonation'}},
    [953] = {en='Dragon Breath',skillchain={'Light','Fusion'}},
    [956] = {en='Hurricane Wing',skillchain={'Scission','Detonation'}},
    [968] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [969] = {en='Flat Blade',skillchain={'Impaction'}},
    [970] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [973] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [975] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [979] = {en='Power Slash',skillchain={'Transfixion'}},
    [980] = {en='Freezebite',skillchain={'Induration','Detonation'}},
    [981] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
    [985] = {en='Stellar Burst',skillchain={'Darkness','Gravitation'}},
    [986] = {en='Vortex',skillchain={'Distortion','Reverberation'}},
    [987] = {en='Shockwave',skillchain={'Reverberation'}},
    [1027] = {en='Combo',skillchain={'Impaction'}},
    [1029] = {en='One-Ilm Punch',skillchain={'Compression'}},
    [1030] = {en='Backhand Blow',skillchain={'Detonation'}},
    [1031] = {en='Spinning Attack',skillchain={'Liquefaction','Impaction'}},
    [1032] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
    [1033] = {en='Dragon Kick',skillchain={'Fragmentation'}},
    [1034] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
    [1039] = {en='Hurricane Wing',skillchain={'Scission','Detonation'}},
    [1041] = {en='Dragon Breath',skillchain={'Light','Fusion'}},
    [1088] = {en='Goblin Rush',skillchain={'Fusion','Impaction'}},
    [1089] = {en='Bomb Toss',skillchain={'Liquefaction'}},
    [1090] = {en='Bomb Toss',skillchain={'Liquefaction'}},
    [1188] = {en='Final Heaven',skillchain={'Light','Fusion'}},
    [1189] = {en='Mercy Stroke',skillchain={'Darkness','Gravitation'}},
    [1190] = {en='Knights of Round',skillchain={'Light','Fusion'}},
    [1191] = {en='Scourge',skillchain={'Light','Fusion'}},
    [1192] = {en='Onslaught',skillchain={'Darkness','Gravitation'}},
    [1193] = {en='Metatron Torment',skillchain={'Light','Fusion'}},
    [1194] = {en='Catastrophe',skillchain={'Darkness','Gravitation'}},
    [1195] = {en='Geirskogul',skillchain={'Light','Distortion'}},
    [1196] = {en='Blade: Metsu',skillchain={'Darkness','Fragmentation'}},
    [1197] = {en='Tachi: Kaiten',skillchain={'Light','Fragmentation'}},
    [1198] = {en='Randgrith',skillchain={'Light','Fragmentation'}},
    [1199] = {en='Gate of Tartarus',skillchain={'Darkness','Distortion'}},
    [1201] = {en='Coronach',skillchain={'Darkness','Fragmentation'}},
    [1390] = {en='Amatsu: Torimai',skillchain={'Transfixion','Scission'}},
    [1391] = {en='Amatsu: Kazakiri',skillchain={'Scission','Detonation'}},
    [1392] = {en='Amatsu: Yukiarashi',skillchain={'Induration','Detonation'}},
    [1393] = {en='Amatsu: Tsukioboro',skillchain={'Distortion','Reverberation'}},
    [1394] = {en='Amatsu: Hanaikusa',skillchain={'Fusion','Compression'}},
    [1395] = {en='Amatsu: Tsukikage',skillchain={'Darkness','Fragmentation'}},
    [1397] = {en='Oisoya',skillchain={'Light','Distortion'}},
    [1444] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [1476] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [1477] = {en='Flat Blade',skillchain={'Impaction'}},
    [1478] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [1481] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [1483] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [1489] = {en='Nullifying Dropkick',skillchain={'Induration','Detonation','Impaction'}},
    [1490] = {en='Auroral Uppercut',skillchain={'Light','Fragmentation'}},
    [1508] = {en='Luminous Lance',skillchain={'Light','Fusion'},delay=7},
    [1510] = {en='Revelation',skillchain={'Fusion','Transfixion'},delay=6},
    [1517] = {en='Goblin Rush',skillchain={'Fusion','Impaction'}},
    [1520] = {en='Howling Moon',skillchain={'Darkness','Distortion'}},
    [1586] = {en='Wild Oats',skillchain={'Transfixion'}},
    [1618] = {en='Uppercut',skillchain={'Liquefaction'}},
    [1737] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [1854] = {en='Stellar Burst',skillchain={'Darkness','Gravitation'}},
    [1914] = {en='Great Wheel',skillchain={'Fragmentation','Scission'}},
    [1936] = {en='Shibaraku',skillchain={'Darkness','Gravitation'}},
    [1940] = {en='Chimera Ripper',skillchain={'Induration','Detonation'}},
    [1941] = {en='String Clipper',skillchain={'Scission','Impaction'}},
    [1942] = {en='Arcuballista',skillchain={'Liquefaction','Transfixion'}},
    [1943] = {en='Slapstick',skillchain={'Reverberation','Impaction'}},
    [1982] = {en='Nullifying Dropkick',skillchain={'Induration','Detonation','Impaction'}},
    [1983] = {en='Auroral Uppercut',skillchain={'Light','Fragmentation'}},
    [1998] = {en='Hane Fubuki',skillchain={'Transfixion'}},
    [2001] = {en='Happobarai',skillchain={'Reverberation','Impaction'}},
    [2065] = {en='Cannibal Blade',skillchain={'Compression','Reverberation'}},
    [2066] = {en='Daze',skillchain={'Transfixion'}},
    [2067] = {en='Knockout',skillchain={'Scission','Detonation'}},
    [2088] = {en='Victory Beacon',skillchain={'Light','Distortion'}},
    [2089] = {en='Salamander Flame',skillchain={'Light','Fusion'}},
    [2090] = {en='Typhonic Arrow',skillchain={'Light','Fragmentation'}},
    [2091] = {en='Meteoric Impact',skillchain={'Darkness','Fragmentation'}},
    [2092] = {en='Scouring Bubbles',skillchain={'Darkness','Distortion'}},
    [2134] = {en='Victory Beacon',skillchain={'Light','Distortion'}},
    [2135] = {en='Salamander Flame',skillchain={'Light','Fusion'}},
    [2136] = {en='Typhonic Arrow',skillchain={'Light','Fragmentation'}},
    [2137] = {en='Meteoric Impact',skillchain={'Darkness','Fragmentation'}},
    [2138] = {en='Scouring Bubbles',skillchain={'Darkness','Distortion'}},
    [2140] = {en='Peacebreaker',skillchain={'Distortion','Reverberation'}},
    [2272] = {en='Bear Killer',skillchain={'Reverberation','Impaction'}},
    [2273] = {en='Uriel Blade',skillchain={'Light','Fragmentation'}},
    [2274] = {en='Spine Chiller',skillchain={'Distortion','Detonation'}},
    [2278] = {en='Glory Slash',skillchain={'Light','Fusion'}},
    [2280] = {en='Iainuki',skillchain={'Light','Fragmentation'},delay=7},
    [2299] = {en='Bone Crusher',skillchain={'Fragmentation'}},
    [2300] = {en='Armor Piercer',skillchain={'Gravitation'}},
    [2301] = {en='Magic Mortar',skillchain={'Fusion'}},
    [2386] = {en='Cobra Clamp',skillchain={'Fragmentation','Distortion'}},
    [2444] = {en='Dancer\'s Fury',skillchain={'Fragmentation','Scission'}},
    [2445] = {en='Whirling Edge',skillchain={'Distortion','Reverberation'}},
    [2468] = {en='King Cobra Clamp',skillchain={'Fragmentation','Distortion'}},
    [2469] = {en='Wasp Sting',skillchain={'Scission'}},
    [2470] = {en='Dancing Edge',skillchain={'Scission','Detonation'}},
    [2472] = {en='Songbird Swoop',skillchain={'Reverberation','Impaction'}},
    [2476] = {en='Gyre Strike',skillchain={'Fragmentation'}},
    [2477] = {en='Stag\'s Charge',skillchain={'Gravitation','Induration'}},
    [2478] = {en='Orcsbane',skillchain={'Light','Distortion'}},
    [2479] = {en='Temblor Blade',skillchain={'Reverberation','Impaction'}},
    [2486] = {en='Salvation Scythe',skillchain={'Darkness'}},
    [2487] = {en='Salvation Scythe',skillchain={'Darkness'}},
    [2588] = {en='Debonair Rush',skillchain={'Scission','Detonation'}},
    [2589] = {en='Iridal Pierce',skillchain={'Light','Fragmentation'}},
    [2590] = {en='Lunar Revolution',skillchain={'Gravitation','Reverberation'}},
    [2594] = {en='Quietus Sphere',skillchain={'Darkness','Gravitation'}},
    [2743] = {en='String Shredder',skillchain={'Distortion','Scission'}},
    [2744] = {en='Armor Shatterer',skillchain={'Fusion','Impaction'}},
    [2891] = {en='Grapeshot',skillchain={'Reverberation','Transfixion'}},
    [2892] = {en='Pirate Pummel',skillchain={'Fusion','Impaction'}},
    [2893] = {en='Powder Keg',skillchain={'Fusion','Compression'}},
    [2894] = {en='Walk the Plank',skillchain={'Light','Distortion'}},
    [2895] = {en='Knuckle Sandwich',skillchain={'Fusion','Compression'}},
    [2896] = {en='Imperial Authority',skillchain={'Fragmentation','Distortion'}},
    [2897] = {en='Sixth Element',skillchain={'Darkness','Gravitation'}},
    [2898] = {en='Shield Subverter',skillchain={'Light','Fusion'}},
    [2899] = {en='Shining Summer Samba',skillchain={'Liquefaction','Transfixion'}},
    [2900] = {en='Lovely Miracle Waltz',skillchain={'Liquefaction','Scission','Impaction'}},
    [2901] = {en='Neo Crystal Jig',skillchain={'Fusion','Transfixion'}},
    [2902] = {en='Super Crusher Jig',skillchain={'Gravitation','Reverberation'},delay=7},
    [3161] = {en='Camaraderie of the Crevasse',skillchain={'Detonation','Impaction'}},
    [3162] = {en='Into the Light',skillchain={'Fusion','Impaction'}},
    [3163] = {en='Arduous Decision',skillchain={'Fragmentation','Compression'}},
    [3164] = {en='12 Blades of Remorse',skillchain={'Light','Distortion'}},
    [3168] = {en='Aurous Charge',skillchain={'Liquefaction','Transfixion'}},
    [3169] = {en='Howling Gust',skillchain={'Fragmentation','Compression'},delay=6},
    [3170] = {en='Righteous Rasp',skillchain={'Fusion','Transfixion'}},
    [3171] = {en='Starward Yowl',skillchain={'Gravitation','Reverberation'}},
    [3172] = {en='Stalking Prey',skillchain={'Light','Fragmentation'}},
    [3176] = {en='Chant du Cygne',skillchain={'Light','Distortion'}},
    [3179] = {en='Chant du Cygne',skillchain={'Light','Distortion'}},
    [3185] = {en='Cloudsplitter',skillchain={'Darkness','Fragmentation'}},
    [3188] = {en='Tachi: Fudo',skillchain={'Light','Distortion'}},
    [3189] = {en='King Cobra Clamp',skillchain={'Fragmentation','Distortion'}},
    [3190] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [3192] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [3197] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
    [3198] = {en='Grapeshot',skillchain={'Reverberation','Transfixion'}},
    [3199] = {en='Pirate Pummel',skillchain={'Fusion','Impaction'}},
    [3200] = {en='Powder Keg',skillchain={'Fusion','Compression'}},
    [3201] = {en='Walk the Plank',skillchain={'Light','Distortion'}},
    [3202] = {en='Uriel Blade',skillchain={'Light','Fragmentation'}},
    [3203] = {en='Scouring Bubbles',skillchain={'Darkness','Distortion'}},
    [3204] = {en='Amatsu: Tsukikage',skillchain={'Darkness','Fragmentation'}},
    [3213] = {en='Vortex',skillchain={'Distortion','Reverberation'}},
    [3214] = {en='Light Blade',skillchain={'Light','Fusion'}},
    [3215] = {en='Peacebreaker',skillchain={'Distortion','Reverberation'}},
    [3216] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
    [3217] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [3231] = {en='Debonair Rush',skillchain={'Scission','Detonation'}},
    [3232] = {en='Iridal Pierce',skillchain={'Light','Fragmentation'}},
    [3233] = {en='Lunar Revolution',skillchain={'Gravitation','Reverberation'}},
    [3234] = {en='Nullifying Dropkick',skillchain={'Induration','Detonation','Impaction'}},
    [3235] = {en='Auroral Uppercut',skillchain={'Light','Fragmentation'}},
    [3236] = {en='Knuckle Sandwich',skillchain={'Fusion','Compression'}},
    [3237] = {en='Victory Beacon',skillchain={'Light','Distortion'}},
    [3238] = {en='Salamander Flame',skillchain={'Light','Fusion'}},
    [3239] = {en='Typhonic Arrow',skillchain={'Light','Fragmentation'}},
    [3240] = {en='Meteoric Impact',skillchain={'Darkness','Fragmentation'}},
    [3243] = {en='Imperial Authority',skillchain={'Fragmentation','Distortion'}},
    [3244] = {en='Sixth Element',skillchain={'Darkness','Gravitation'}},
    [3245] = {en='Shield Subverter',skillchain={'Light','Fusion'}},
    [3252] = {en='Bisection',skillchain={'Scission','Detonation'}},
    [3253] = {en='Leaden Salute',skillchain={'Gravitation','Transfixion'}},
    [3254] = {en='Akimbo Shot',skillchain={'Compression'},delay=5},
    [3255] = {en='Grisly Horizon',skillchain={'Darkness','Distortion'}},
    [3256] = {en='Hane Fubuki',skillchain={'Transfixion'}},
    [3257] = {en='Shibaraku',skillchain={'Darkness','Gravitation'}},
    [3259] = {en='Happobarai',skillchain={'Reverberation','Impaction'}},
    [3261] = {en='Bomb Toss',skillchain={'Liquefaction'}},
    [3262] = {en='Goblin Rush',skillchain={'Fusion','Impaction'}},
    [3263] = {en='Bear Killer',skillchain={'Reverberation','Impaction'}},
    [3264] = {en='Salvation Scythe',skillchain={'Darkness'}},
    [3283] = {en='Iniquitous Stab',skillchain={'Gravitation','Transfixion'}},
    [3284] = {en='Shockstorm Edge',skillchain={'Detonation','Impaction'}},
    [3285] = {en='Choreographed Carnage',skillchain={'Darkness','Distortion'}},
    [3286] = {en='Lock and Load',skillchain={'Fusion','Reverberation'}},
    [3292] = {en='Gyre Strike',skillchain={'Fragmentation'}},
    [3293] = {en='Stag\'s Charge',skillchain={'Gravitation','Induration'}},
    [3294] = {en='Orcsbane',skillchain={'Light','Distortion'}},
    [3295] = {en='Songbird Swoop',skillchain={'Reverberation','Impaction'}},
    [3296] = {en='Temblor Blade',skillchain={'Reverberation','Impaction'}},
    [3297] = {en='Cobra Clamp',skillchain={'Fragmentation','Distortion'}},
    [3303] = {en='Feast of Arrows',skillchain={'Gravitation','Transfixion'}},
    [3305] = {en='Regurgitated Swarm',skillchain={'Fusion','Compression'},delay=7},
    [3306] = {en='Setting the Stage',skillchain={'Gravitation','Induration'}},
    [3307] = {en='Last Laugh',skillchain={'Darkness','Gravitation'}},
    [3310] = {en='Dancer\'s Fury',skillchain={'Fragmentation','Scission'}},
    [3311] = {en='Whirling Edge',skillchain={'Distortion','Reverberation'}},
    [3314] = {en='True Strike',skillchain={'Detonation','Impaction'}},
    [3315] = {en='Hexa Strike',skillchain={'Fusion'}},
    [3322] = {en='Critical Mass',skillchain={'Fusion','Impaction'}},
    [3323] = {en='Fiery Tailings',skillchain={'Light','Fusion'}},
    [3336] = {en='Howling Moon',skillchain={'Darkness','Distortion'}},
    [3337] = {en='Lunar Bay',skillchain={'Gravitation','Transfixion'}},
    [3351] = {en='Wild Oats',skillchain={'Transfixion'}},
    [3356] = {en='Uppercut',skillchain={'Liquefaction'}},
    [3381] = {en='Frenzied Thrust',skillchain={'Fragmentation','Transfixion'}},
    [3382] = {en='Sinner\'s Cross',skillchain={'Gravitation','Scission'}},
    [3383] = {en='Open Coffin',skillchain={'Fusion','Compression'}},
    [3385] = {en='Hemocladis',skillchain={'Darkness','Distortion'}},
    [3411] = {en='Power Slash',skillchain={'Transfixion'}},
    [3412] = {en='Freezebite',skillchain={'Induration','Detonation'}},
    [3413] = {en='Combo',skillchain={'Impaction'}},
    [3414] = {en='One-Ilm Punch',skillchain={'Compression'}},
    [3415] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
    [3416] = {en='Dragon Kick',skillchain={'Fragmentation'}},
    [3417] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
    [3418] = {en='Amatsu: Torimai',skillchain={'Transfixion','Scission'}},
    [3419] = {en='Amatsu: Kazakiri',skillchain={'Scission','Detonation'}},
    [3420] = {en='Amatsu: Yukiarashi',skillchain={'Induration','Detonation'}},
    [3421] = {en='Amatsu: Tsukioboro',skillchain={'Distortion','Reverberation'}},
    [3422] = {en='Amatsu: Hanaikusa',skillchain={'Fusion','Compression'}},
    [3423] = {en='Wasp Sting',skillchain={'Scission'}},
    [3424] = {en='Dancing Edge',skillchain={'Scission','Detonation'}},
    [3425] = {en='Flat Blade',skillchain={'Impaction'}},
    [3431] = {en='Fast Blade',skillchain={'Scission'}},
    [3432] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
    [3434] = {en='Tachi: Kamai',skillchain={'Gravitation','Scission'}},
    [3435] = {en='Iainuki',skillchain={'Light','Fragmentation'},delay=7},
    [3436] = {en='Tachi: Goten',skillchain={'Transfixion','Impaction'}},
    [3437] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [3438] = {en='Dragon Breath',skillchain={'Light','Fusion'}},
    [3439] = {en='Hurricane Wing',skillchain={'Scission','Detonation'}},
    [3445] = {en='Merciless Strike',skillchain={'Detonation','Impaction'}},
    [3448] = {en='Uppercut',skillchain={'Liquefaction'}},
    [3454] = {en='Coming Up Roses',skillchain={'Light','Fusion'},delay=7},
    [3466] = {en='Paralyzing Microtube',skillchain={'Induration'},delay=6},
    [3467] = {en='Silencing Microtube',skillchain={'Liquefaction','Detonation'},delay=6},
    [3468] = {en='Binding Microtube',skillchain={'Gravitation','Induration'},delay=6},
    [3469] = {en='Twirling Dervish',skillchain={'Light','Fusion'},delay=8},
    [3470] = {en='Great Wheel',skillchain={'Fragmentation','Scission'}},
    [3471] = {en='Light Blade',skillchain={'Light','Fusion'}},
    [3472] = {en='Vortex',skillchain={'Distortion','Reverberation'}},
    [3473] = {en='Stellar Burst',skillchain={'Darkness','Gravitation'}},
    [3487] = {en='Sidewinder',skillchain={'Reverberation','Transfixion','Detonation'}},
    [3488] = {en='Arching Arrow',skillchain={'Fusion'}},
    [3489] = {en='Stellar Arrow',skillchain={'Darkness','Gravitation'}},
    [3490] = {en='Lux Arrow',skillchain={'Fragmentation','Distortion'}},
    [3491] = {en='Grapeshot',skillchain={'Reverberation','Transfixion'}},
    [3492] = {en='Pirate Pummel',skillchain={'Fusion','Impaction'}},
    [3493] = {en='Powder Keg',skillchain={'Fusion','Compression'}},
    [3494] = {en='Walk the Plank',skillchain={'Light','Distortion'}},
    [3495] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
    [3496] = {en='Hollow Smite',skillchain={'Light','Fragmentation'}},
    [3497] = {en='Sarva\'s Storm',skillchain={'Darkness','Distortion'}},
    [3498] = {en='Sarva\'s Storm',skillchain={'Darkness','Distortion'}},
    [3499] = {en='Soturi\'s Fury',skillchain={'Light','Fragmentation'}},
    [3500] = {en='Celidon\'s Torment',skillchain={'Light','Fragmentation'}},
    [3501] = {en='Tachi: Mudo',skillchain={'Light','Distortion'}},
    [3503] = {en='Justicebreaker',skillchain={'Darkness','Gravitation'},delay=5},
    [3536] = {en='Spine Chiller',skillchain={'Distortion','Detonation'}},
    [3537] = {en='Quietus Sphere',skillchain={'Darkness','Gravitation'}},
    [3538] = {en='Null Blast',skillchain={'Fusion','Compression'}},
    [3542] = {en='Oisoya',skillchain={'Light','Distortion'}},
    [3543] = {en='Knuckle Sandwich',skillchain={'Fusion','Compression'}},
    [3544] = {en='Whirling Edge',skillchain={'Distortion','Reverberation'}},
    [3551] = {en='Lunar Bay',skillchain={'Gravitation','Transfixion'}},
    [3556] = {en='Amatsu: Fuga',skillchain={'Impaction'},delay=6},
    [3557] = {en='Amatsu: Kyori',skillchain={'Induration'},delay=7},
    [3558] = {en='Amatsu: Hanadoki',skillchain={'Reverberation','Impaction'}},
    [3559] = {en='Amatsu: Choun',skillchain={'Liquefaction'}},
    [3560] = {en='Amatsu: Gachirin',skillchain={'Light','Fragmentation'},delay=7},
    [3561] = {en='Amatsu: Suien',skillchain={'Fusion'},delay=6},
    [3579] = {en='Expunge Magic',skillchain={'Distortion','Scission'}},
    [3580] = {en='Harmonic Displacement',skillchain={'Fusion','Reverberation'}},
    [3581] = {en='Sight Unseen',skillchain={'Fragmentation','Compression'}},
    [3582] = {en='Darkest Hour',skillchain={'Gravitation','Liquefaction'}},
    [3585] = {en='Naakual\'s Vengeance',skillchain={'Light','Fusion'},delay=7},
    [3591] = {en='Tartaric Sigil',skillchain={'Compression','Scission'}},
    [3592] = {en='Null Field',skillchain={'Fusion','Transfixion'}},
    [3593] = {en='Alabaster Burst',skillchain={'Distortion','Detonation'}},
    [3594] = {en='Noble Frenzy',skillchain={'Gravitation','Scission'}},
    [3595] = {en='Fulminous Fury',skillchain={'Fragmentation','Scission'},delay=6},
    [3596] = {en='No Quarter',skillchain={'Light','Distortion'},delay=7},
    [3611] = {en='Inexorable Strike',skillchain={'Light','Fusion'}},
    [3617] = {en='Feast of Arrows',skillchain={'Gravitation','Transfixion'}},
    [3618] = {en='Regurgitated Swarm',skillchain={'Fusion','Compression'},delay=7},
    [3619] = {en='Setting the Stage',skillchain={'Gravitation','Induration'}},
    [3620] = {en='Last Laugh',skillchain={'Darkness','Gravitation'}},
    [3621] = {en='Luminous Lance',skillchain={'Light','Fusion'},delay=7},
    [3623] = {en='Revelation',skillchain={'Fusion','Transfixion'},delay=6},
    [3632] = {en='Frenzied Thrust',skillchain={'Fragmentation','Transfixion'}},
    [3633] = {en='Sinner\'s Cross',skillchain={'Gravitation','Scission'}},
    [3634] = {en='Open Coffin',skillchain={'Fusion','Compression'}},
    [3636] = {en='Hemocladis',skillchain={'Darkness','Distortion'}},
    [3637] = {en='Shining Summer Samba',skillchain={'Liquefaction','Transfixion'}},
    [3638] = {en='Lovely Miracle Waltz',skillchain={'Liquefaction','Scission','Impaction'}},
    [3639] = {en='Neo Crystal Jig',skillchain={'Fusion','Transfixion'}},
    [3640] = {en='Super Crusher Jig',skillchain={'Gravitation','Reverberation'},delay=7},
    [3645] = {en='Inexorable Strike',skillchain={'Light','Fusion'}},
    [3647] = {en='Merciless Strike',skillchain={'Detonation','Impaction'}},
    [3653] = {en='Tartaric Sigil',skillchain={'Compression','Scission'}},
    [3654] = {en='Null Field',skillchain={'Fusion','Transfixion'}},
    [3655] = {en='Alabaster Burst',skillchain={'Distortion','Detonation'}},
    [3656] = {en='Noble Frenzy',skillchain={'Gravitation','Scission'}},
    [3657] = {en='Fulminous Fury',skillchain={'Fragmentation','Scission'},delay=6},
    [3658] = {en='No Quarter',skillchain={'Light','Distortion'},delay=7},
    [3677] = {en='Camaraderie of the Crevasse',skillchain={'Detonation','Impaction'}},
    [3678] = {en='Into the Light',skillchain={'Fusion','Impaction'}},
    [3679] = {en='Arduous Decision',skillchain={'Fragmentation','Compression'}},
    [3680] = {en='12 Blades of Remorse',skillchain={'Light','Distortion'}},
    [3684] = {en='Aurous Charge',skillchain={'Liquefaction','Transfixion'}},
    [3685] = {en='Howling Gust',skillchain={'Fragmentation','Compression'},delay=6},
    [3686] = {en='Righteous Rasp',skillchain={'Fusion','Transfixion'}},
    [3687] = {en='Starward Yowl',skillchain={'Gravitation','Reverberation'}},
    [3688] = {en='Stalking Prey',skillchain={'Light','Fragmentation'}},
    [3691] = {en='Bludgeon',skillchain={'Fusion'}},
    [3699] = {en='Expunge Magic',skillchain={'Distortion','Scission'}},
    [3700] = {en='Harmonic Displacement',skillchain={'Fusion','Reverberation'}},
    [3701] = {en='Sight Unseen',skillchain={'Fragmentation','Compression'}},
    [3702] = {en='Darkest Hour',skillchain={'Gravitation','Liquefaction'}},
    [3705] = {en='Naakual\'s Vengeance',skillchain={'Light','Fusion'},delay=7},
    [3707] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
    [3708] = {en='Swift Blade',skillchain={'Gravitation'}},
    [3709] = {en='Chant du Cygne',skillchain={'Light','Distortion'}},
    [3711] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
    [3713] = {en='Chant du Cygne',skillchain={'Light','Distortion'}},
    [3715] = {en='Rampage',skillchain={'Scission'}},
    [3716] = {en='Calamity',skillchain={'Scission','Impaction'}},
    [3718] = {en='Cloudsplitter',skillchain={'Darkness','Fragmentation'}},
    [3719] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
    [3721] = {en='Guillotine',skillchain={'Induration'}},
    [3722] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
    [3723] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
    [3725] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
    [3726] = {en='Tachi: Fudo',skillchain={'Light','Distortion'}},
    [3732] = {en='Amatsu: Fuga',skillchain={'Impaction'},delay=6},
    [3733] = {en='Amatsu: Kyori',skillchain={'Induration'},delay=7},
    [3734] = {en='Amatsu: Hanadoki',skillchain={'Reverberation','Impaction'}},
    [3735] = {en='Amatsu: Choun',skillchain={'Liquefaction'}},
    [3736] = {en='Amatsu: Gachirin',skillchain={'Light','Fragmentation'},delay=7},
    [3737] = {en='Amatsu: Suien',skillchain={'Fusion'},delay=6},
    [3740] = {en='Final Exam',skillchain={'Light','Fusion'}},
    [3741] = {en='Doctor\'s Orders',skillchain={'Darkness','Gravitation'}},
    [3742] = {en='Empirical Research',skillchain={'Fragmentation','Transfixion'}},
    [3743] = {en='Lesson in Pain',skillchain={'Distortion','Scission'}},
    [3840] = {en='Foot Kick',skillchain={'Reverberation'}},
    [3842] = {en='Whirl Claws',skillchain={'Impaction'}},
    [3843] = {en='Head Butt',skillchain={'Detonation'}},
    [3845] = {en='Wild Oats',skillchain={'Transfixion'}},
    [3846] = {en='Leaf Dagger',skillchain={'Scission'}},
    [3849] = {en='Razor Fang',skillchain={'Impaction'}},
    [3850] = {en='Claw Cyclone',skillchain={'Scission'}},
    [3851] = {en='Tail Blow',skillchain={'Impaction'}},
    [3853] = {en='Blockhead',skillchain={'Reverberation'}},
    [3854] = {en='Brain Crush',skillchain={'Liquefaction'}},
    [3857] = {en='Lamb Chop',skillchain={'Impaction'}},
    [3859] = {en='Sheep Charge',skillchain={'Reverberation'}},
    [3863] = {en='Big Scissors',skillchain={'Scission'}},
    [3866] = {en='Needleshot',skillchain={'Transfixion'}},
    [3867] = {en='??? Needles',skillchain={'Darkness','Fragmentation'}},
    [3868] = {en='Frogkick',skillchain={'Compression'}},
    [3875] = {en='Power Attack',skillchain={'Reverberation'}},
    [3877] = {en='Rhino Attack',skillchain={'Detonation'}},
    [3885] = {en='Mandibular Bite',skillchain={'Detonation'}},
    [3891] = {en='Nimble Snap',skillchain={'Impaction'}},
    [3892] = {en='Cyclotail',skillchain={'Impaction'}},
    [3894] = {en='Double Claw',skillchain={'Liquefaction'}},
    [3895] = {en='Grapple',skillchain={'Reverberation'}},
    [3897] = {en='Spinning Top',skillchain={'Impaction'}},
    [3900] = {en='Suction',skillchain={'Compression'}},
    [3904] = {en='Sudden Lunge',skillchain={'Impaction'}},
    [3905] = {en='Spiral Spin',skillchain={'Scission'}},
    [3909] = {en='Scythe Tail',skillchain={'Liquefaction'}},
    [3910] = {en='Ripper Fang',skillchain={'Induration'}},
    [3911] = {en='Chomp Rush',skillchain={'Darkness','Gravitation'}},
    [3915] = {en='Back Heel',skillchain={'Reverberation'}},
    [3919] = {en='Tortoise Stomp',skillchain={'Liquefaction'}},
    [3922] = {en='Wing Slap',skillchain={'Gravitation','Liquefaction'}},
    [3923] = {en='Beak Lunge',skillchain={'Scission'}},
    [3925] = {en='Recoil Dive',skillchain={'Transfixion'}},
    [3927] = {en='Sensilla Blades',skillchain={'Scission'}},
    [3928] = {en='Tegmina Buffet',skillchain={'Distortion','Detonation'}},
    [3930] = {en='Swooping Frenzy',skillchain={'Fusion','Reverberation'}},
    [3931] = {en='Sweeping Gouge',skillchain={'Induration'}},
    [3933] = {en='Pentapeck',skillchain={'Light','Distortion'}},
    [3934] = {en='Tickling Tendrils',skillchain={'Impaction'}},
    [3938] = {en='Somersault',skillchain={'Compression'}},
    [3941] = {en='Pecking Flurry',skillchain={'Transfixion'}},
    [3942] = {en='Sickle Slash',skillchain={'Transfixion'}},
    [4050] = {en='Wild Oats',skillchain={'Transfixion'}},
    [4124] = {en='Bomb Toss',skillchain={'Liquefaction'}},
    [4158] = {en='Blade: Metsu',skillchain={'Darkness','Fragmentation'}},
    [4211] = {en='Iniquitous Stab',skillchain={'Gravitation','Transfixion'}},
    [4212] = {en='Shockstorm Edge',skillchain={'Detonation','Impaction'}},
    [4213] = {en='Choreographed Carnage',skillchain={'Darkness','Distortion'}},
    [4214] = {en='Lock and Load',skillchain={'Fusion','Reverberation'}},
}

-- Job Abilities that are able to form a Skillchain or Magic Burst (DRG, SMN)
skills.job_abilities = {
    -- Dragoon's Breath
	[318] = {en='Smiting Breath',element={'Fire','Ice','Wind','Earth','Lightning','Water'}},

	-- Blood Pacts
	[516] = {en='Meteorite',element={'Light'}},
	[518] = {en='Searing Light',element={'Light'}},
    [519] = {en='Holy Mist',element={'Light'}},
	[513] = {en='Poison Nails',skillchain={'Transfixion'}},
    [521] = {en='Regal Scratch',skillchain={'Scission'}},
	[522] = {en='Mewing Lullaby',element={'Light'}},
    [523] = {en='Eerie Eye',element={'Light'}},
    [524] = {en='Level ? Holy',element={'Light'}},
    [528] = {en='Moonlit Charge',skillchain={'Compression'}},
    [529] = {en='Crescent Fang',skillchain={'Transfixion'}},
	[530] = {en='Lunar Cry',element={'Dark'}},
    [531] = {en='Lunar Roar',element={'Dark'}},
    [534] = {en='Eclipse Bite',skillchain={'Gravitation','Scission'}},
	[536] = {en='Howling Moon',element={'Dark'}},
    [537] = {en='Lunar Bay',element={'Dark'}},
    [539] = {en='Impact',element={'Dark'}},
    [544] = {en='Punch',skillchain={'Liquefaction'}},
	[545] = {en='Fire II',element={'Fire'}},
    [546] = {en='Burning Strike',skillchain={'Impaction'}},
    [547] = {en='Double Punch',skillchain={'Compression'}},
	[549] = {en='Fire IV',element={'Fire'}},
    [550] = {en='Flaming Crush',skillchain={'Fusion','Reverberation'}},
	[551] = {en='Meteor Strike',element={'Fire'}},
    [552] = {en='Inferno',element={'Fire'}},
    [554] = {en='Conflag Strike',element={'Fire'}},
    [560] = {en='Rock Throw',skillchain={'Scission'}},
	[561] = {en='Stone II',element={'Earth'}},
    [562] = {en='Rock Buster',skillchain={'Reverberation'}},
    [563] = {en='Megalith Throw',skillchain={'Induration'}},
	[565] = {en='Stone IV',element={'Earth'}},
    [566] = {en='Mountain Buster',skillchain={'Gravitation','Induration'}},
	[567] = {en='Geocrush',element={'Earth'}},
    [568] = {en='Earthen Fury',element={'Earth'}},
    [570] = {en='Crag Throw',skillchain={'Gravitation','Scission'}},
    [576] = {en='Barracuda Dive',skillchain={'Reverberation'}},
	[577] = {en='Water II',element={'Water'}},
    [578] = {en='Tail Whip',skillchain={'Detonation'}},
	[580] = {en='Slowga',element={'Water'}},
    [581] = {en='Water IV',element={'Water'}},
    [582] = {en='Spinning Dive',skillchain={'Distortion','Detonation'}},
	[583] = {en='Grand Fall',element={'Water'}},
    [584] = {en='Tidal Wave',element={'Water'}},
    [585] = {en='Tidal Roar',element={'Water'}},
    [592] = {en='Claw',skillchain={'Detonation'}},
	[593] = {en='Aero II',element={'Wind'}},
    [597] = {en='Aero IV',element={'Wind'}},
    [598] = {en='Predator Claws',skillchain={'Fragmentation','Scission'}},
	[599] = {en='Wind Blade',element={'Wind'}},
	[600] = {en='Aerial Blast',element={'Wind'}},
    [608] = {en='Axe Kick',skillchain={'Induration'}},
	[609] = {en='Blizzard II',element={'Ice'}},
    [611] = {en='Sleepga',element={'Ice'}},
    [612] = {en='Double Slap',skillchain={'Scission'}},
	[613] = {en='Blizzard IV',element={'Ice'}},
    [614] = {en='Rush',skillchain={'Distortion','Scission'}},
	[615] = {en='Heavenly Strike',element={'Ice'}},
	[616] = {en='Diamond Dust',element={'Ice'}},
    [617] = {en='Diamond Storm',element={'Ice'}},
    [624] = {en='Shock Strike',skillchain={'Impaction'}},
	[625] = {en='Thunder II',element={'Lightning'}},
    [627] = {en='Thunderspark',element={'Lightning'}},
    [629] = {en='Thunder IV',element={'Lightning'}},
    [630] = {en='Chaotic Strike',skillchain={'Fragmentation','Transfixion'}},
	[631] = {en='Thunderstorm',element={'Lightning'}},
    [632] = {en='Judgment Bolt',element={'Lightning'}},
    [633] = {en='Shock Squall',element={'Lightning'}},
    [634] = {en='Volt Strike',skillchain={'Fragmentation','Scission'}},
    [656] = {en='Camisado',skillchain={'Compression'}},
	[657] = {en='Somnolence',element={'Dark'}},
    [658] = {en='Nightmare',element={'Dark'}},
    [659] = {en='Ultimate Terror',element={'Dark'}},
	[662] = {en='Nether Blast',element={'Dark'}},
    [664] = {en='Ruinous Omen',element={'Dark'}},
    [665] = {en='Night Terror',element={'Dark'}},
	[666] = {en='Pavor Nocturnus',element={'Dark'}},
    [667] = {en='Blindside',skillchain={'Gravitation','Transfixion'}},
	[668] = {en='Deconstruction',element={'Dark'}},
	[670] = {en='Zantetsuken',element={'Dark'}},
    [672] = {en='Foot Kick',skillchain={'Reverberation'}},
    [674] = {en='Whirl Claws',skillchain={'Impaction'}},
    [675] = {en='Head Butt',skillchain={'Detonation'}},
    [677] = {en='Wild Oats',skillchain={'Transfixion'}},
    [678] = {en='Leaf Dagger',skillchain={'Scission'}},
    [681] = {en='Razor Fang',skillchain={'Impaction'}},
    [682] = {en='Claw Cyclone',skillchain={'Scission'}},
    [683] = {en='Tail Blow',skillchain={'Impaction'}},
    [685] = {en='Blockhead',skillchain={'Reverberation'}},
    [686] = {en='Brain Crush',skillchain={'Liquefaction'}},
    [689] = {en='Lamb Chop',skillchain={'Impaction'}},
    [691] = {en='Sheep Charge',skillchain={'Reverberation'}},
    [695] = {en='Big Scissors',skillchain={'Scission'}},
    [698] = {en='Needleshot',skillchain={'Transfixion'}},
    [699] = {en='??? Needles',skillchain={'Darkness','Fragmentation'}},
    [700] = {en='Frogkick',skillchain={'Compression'}},
    [707] = {en='Power Attack',skillchain={'Reverberation'}},
    [709] = {en='Rhino Attack',skillchain={'Detonation'}},
    [717] = {en='Mandibular Bite',skillchain={'Detonation'}},
    [723] = {en='Nimble Snap',skillchain={'Impaction'}},
    [724] = {en='Cyclotail',skillchain={'Impaction'}},
    [726] = {en='Double Claw',skillchain={'Liquefaction'}},
    [727] = {en='Grapple',skillchain={'Reverberation'}},
    [728] = {en='Spinning Top',skillchain={'Impaction'}},
    [732] = {en='Suction',skillchain={'Compression'}},
    [736] = {en='Sudden Lunge',skillchain={'Impaction'}},
    [737] = {en='Spiral Spin',skillchain={'Scission'}},
    [743] = {en='Scythe Tail',skillchain={'Liquefaction'}},
    [744] = {en='Ripper Fang',skillchain={'Induration'}},
    [745] = {en='Chomp Rush',skillchain={'Darkness','Gravitation'}},
    [749] = {en='Back Heel',skillchain={'Reverberation'}},
    [753] = {en='Tortoise Stomp',skillchain={'Liquefaction'}},
    [756] = {en='Wing Slap',skillchain={'Gravitation','Liquefaction'}},
    [757] = {en='Beak Lunge',skillchain={'Scission'}},
    [759] = {en='Recoil Dive',skillchain={'Transfixion'}},
    [761] = {en='Sensilla Blades',skillchain={'Scission'}},
    [762] = {en='Tegmina Buffet',skillchain={'Distortion','Detonation'}},
    [764] = {en='Swooping Frenzy',skillchain={'Fusion','Reverberation'}},
    [765] = {en='Sweeping Gouge',skillchain={'Induration'}},
    [767] = {en='Pentapeck',skillchain={'Light','Distortion'}},
    [768] = {en='Tickling Tendrils',skillchain={'Impaction'}},
    [772] = {en='Somersault',skillchain={'Compression'}},
    [776] = {en='Pecking Flurry',skillchain={'Transfixion'}},
    [777] = {en='Sickle Slash',skillchain={'Transfixion'}},
    [780] = {en='Regal Gash',skillchain={'Distortion','Detonation'}},
	[960] = {en='Clarsach Call',element={'Wind'}},
    [961] = {en='Welt',skillchain={'Scission'}},
	[963] = {en='Lunatic Voice',element={'Wind'}},
    [964] = {en='Roundhouse',skillchain={'Detonation'}},
	[966] = {en='Bitter Elegy',element={'Wind'}},
	[967] = {en='Sonic Buffet',element={'Wind'}},
    [968] = {en='Tornado II',element={'Wind'}},
    [970] = {en='Hysteric Assault',skillchain={'Fragmentation','Transfixion'}},
}

-- Runes for Magic Bursting with Swipe / Lunge (RUN)
skills.runes = {
	[1] = {en='Ignis',element={'Fire'}},
    [2] = {en='Gelus',element={'Ice'}},
    [3] = {en='Flabra',element={'Wind'}},
    [4] = {en='Tellus',element={'Earth'}},
    [5] = {en='Sulpor',element={'Lightning'}},
    [6] = {en='Unda',element={'Water'}},
    [7] = {en='Lux',element={'Light'}},
    [8] = {en='Tenebrae',element={'Dark'}},
}

return skills